version: 0.2
phases:
   install:
      runtime-versions:
         docker: 18
   pre_build:
      commands:
      - echo "Entered the pre-build phase"
   build:
      commands:
      - echo "Entered build phase"
      - mvn install -Dmaven.test.skip=true
   post_build:
      commands:
      - echo "Entered the post-build phase"
artifacts:
   files:
   - target/processenion.jar